package View;

/**
 *
 * @author Irsyad Muhamad Al Anshori
 * 
 */
public class viewLoginAdmin extends javax.swing.JFrame {

    /**
     * Creates new form vLoginAdmin
     */
    public viewLoginAdmin() {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(360,640);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelWelcome = new javax.swing.JLabel();
        labelNgampusYuk = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        tfIDAdmin = new javax.swing.JTextField();
        pfPasswordAdmin = new javax.swing.JPasswordField();
        cboxRememberAdmin = new javax.swing.JCheckBox();
        btnLoginAdmin = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        labelWelcome.setBackground(new java.awt.Color(255, 255, 255));
        labelWelcome.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        labelWelcome.setText("Welcome to");
        getContentPane().add(labelWelcome);
        labelWelcome.setBounds(115, 30, 117, 30);

        labelNgampusYuk.setBackground(new java.awt.Color(255, 255, 255));
        labelNgampusYuk.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        labelNgampusYuk.setText("NgampusYuk!");
        getContentPane().add(labelNgampusYuk);
        labelNgampusYuk.setBounds(107, 60, 133, 30);

        labelLogin.setBackground(new java.awt.Color(255, 255, 255));
        labelLogin.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        labelLogin.setText("Login Admin");
        getContentPane().add(labelLogin);
        labelLogin.setBounds(111, 120, 123, 30);

        tfIDAdmin.setText("ID Admin");
        getContentPane().add(tfIDAdmin);
        tfIDAdmin.setBounds(50, 200, 260, 40);

        pfPasswordAdmin.setText("jPasswordField1");
        getContentPane().add(pfPasswordAdmin);
        pfPasswordAdmin.setBounds(50, 255, 260, 40);

        cboxRememberAdmin.setText("Remember Me");
        getContentPane().add(cboxRememberAdmin);
        cboxRememberAdmin.setBounds(50, 305, 130, 23);

        btnLoginAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnLoginAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnLoginAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Next.png"))); // NOI18N
        btnLoginAdmin.setBorder(null);
        btnLoginAdmin.setBorderPainted(false);
        btnLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginAdminActionPerformed(evt);
            }
        });
        getContentPane().add(btnLoginAdmin);
        btnLoginAdmin.setBounds(290, 445, 31, 31);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Grouping.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 360, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLoginAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewLoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewLoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewLoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewLoginAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewLoginAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btnLoginAdmin;
    private javax.swing.JCheckBox cboxRememberAdmin;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelNgampusYuk;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JPasswordField pfPasswordAdmin;
    private javax.swing.JTextField tfIDAdmin;
    // End of variables declaration//GEN-END:variables
}
