package View;

/**
 *
 * @author Irsyad Muhamad Al Anshori
 * 
 */
public class viewCampProfileUnpad extends javax.swing.JFrame {

    /**
     * Creates new form vCampProfileUnpad
     */
    public viewCampProfileUnpad() {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(360,640);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b3BarUnpad = new javax.swing.JButton();
        labelDashboard = new javax.swing.JLabel();
        bLogoutUnpad = new javax.swing.JButton();
        labelLogoUnpad = new javax.swing.JLabel();
        labelUnpad = new javax.swing.JLabel();
        labelAlamat1 = new javax.swing.JLabel();
        labelAlamat2 = new javax.swing.JLabel();
        labelAlamat3 = new javax.swing.JLabel();
        labelTentangKampusUnpad = new javax.swing.JLabel();
        labelDeskripsiUnpad1 = new javax.swing.JLabel();
        labelDeskripsiUnpad2 = new javax.swing.JLabel();
        labelDeskripsiUnpad3 = new javax.swing.JLabel();
        labelDeskripsiUnpad4 = new javax.swing.JLabel();
        labelDeskripsiUnpad5 = new javax.swing.JLabel();
        labelDeskripsiUnpad6 = new javax.swing.JLabel();
        labelDeskripsiUnpad7 = new javax.swing.JLabel();
        labelDeskripsiUnpad8 = new javax.swing.JLabel();
        labelDeskripsiUnpad9 = new javax.swing.JLabel();
        labelDeskripsiUnpad10 = new javax.swing.JLabel();
        labelDeskripsiUnpad11 = new javax.swing.JLabel();
        labelDeskripsiUnpad12 = new javax.swing.JLabel();
        labelDeskripsiUnpad13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        b3BarUnpad.setBackground(new java.awt.Color(255, 255, 255));
        b3BarUnpad.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        b3BarUnpad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button 3 Bar.png"))); // NOI18N
        b3BarUnpad.setBorder(null);
        b3BarUnpad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3BarUnpadActionPerformed(evt);
            }
        });

        labelDashboard.setBackground(new java.awt.Color(255, 255, 255));
        labelDashboard.setFont(new java.awt.Font("Gill Sans MT", 1, 16)); // NOI18N
        labelDashboard.setText("NgampusYuk! Dashboard");

        bLogoutUnpad.setBackground(new java.awt.Color(255, 255, 255));
        bLogoutUnpad.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bLogoutUnpad.setText("Logout");
        bLogoutUnpad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bLogoutUnpad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutUnpadActionPerformed(evt);
            }
        });

        labelLogoUnpad.setBackground(new java.awt.Color(255, 255, 255));
        labelLogoUnpad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Logo PT/Logo Unpad.jpg"))); // NOI18N

        labelUnpad.setBackground(new java.awt.Color(255, 255, 255));
        labelUnpad.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        labelUnpad.setText("Universitas Padjajaran");

        labelAlamat1.setBackground(new java.awt.Color(255, 255, 255));
        labelAlamat1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelAlamat1.setText("Jl. Raya Bandung Sumedang KM. 21");
        labelAlamat1.setMaximumSize(new java.awt.Dimension(648, 15));
        labelAlamat1.setMinimumSize(new java.awt.Dimension(648, 15));
        labelAlamat1.setPreferredSize(new java.awt.Dimension(648, 15));

        labelAlamat2.setBackground(new java.awt.Color(255, 255, 255));
        labelAlamat2.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelAlamat2.setText("Hergarmanah, Jatinangor, Kabupaten");
        labelAlamat2.setMaximumSize(new java.awt.Dimension(648, 15));
        labelAlamat2.setMinimumSize(new java.awt.Dimension(648, 15));
        labelAlamat2.setPreferredSize(new java.awt.Dimension(648, 15));

        labelAlamat3.setBackground(new java.awt.Color(255, 255, 255));
        labelAlamat3.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelAlamat3.setText("Sumedang, Jawa Barat 45363");
        labelAlamat3.setMaximumSize(new java.awt.Dimension(648, 15));
        labelAlamat3.setMinimumSize(new java.awt.Dimension(648, 15));
        labelAlamat3.setPreferredSize(new java.awt.Dimension(648, 15));

        labelTentangKampusUnpad.setBackground(new java.awt.Color(255, 255, 255));
        labelTentangKampusUnpad.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        labelTentangKampusUnpad.setText("Tentang Kampus");

        labelDeskripsiUnpad1.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUnpad1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUnpad1.setText("Universitas Padjajaran (UNPAD) adalah sebuah perguruan");
        labelDeskripsiUnpad1.setMaximumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad1.setMinimumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad1.setPreferredSize(new java.awt.Dimension(648, 15));

        labelDeskripsiUnpad2.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUnpad2.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUnpad2.setText("tinggi negeri di Bandung, Jawa Barat, Indonesia. Pada 20");
        labelDeskripsiUnpad2.setMaximumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad2.setMinimumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad2.setPreferredSize(new java.awt.Dimension(648, 15));

        labelDeskripsiUnpad3.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUnpad3.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUnpad3.setText("Oktober 2014, Universitas ini berubah status menjadi");
        labelDeskripsiUnpad3.setMaximumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad3.setMinimumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad3.setPreferredSize(new java.awt.Dimension(648, 15));

        labelDeskripsiUnpad4.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUnpad4.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUnpad4.setText("Perguruan Tinggi Negeri Badan Hukum (PTN BH) dari Badan");
        labelDeskripsiUnpad4.setMaximumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad4.setMinimumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad4.setPreferredSize(new java.awt.Dimension(648, 15));

        labelDeskripsiUnpad5.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUnpad5.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUnpad5.setText("Layanan Umum (BLU). Peresmian itu ditandai dengan");
        labelDeskripsiUnpad5.setMaximumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad5.setMinimumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad5.setPreferredSize(new java.awt.Dimension(648, 15));

        labelDeskripsiUnpad6.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUnpad6.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUnpad6.setText("peraturan pemerintah (PP) yang ditandatangani oleh mantan");
        labelDeskripsiUnpad6.setMaximumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad6.setMinimumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad6.setPreferredSize(new java.awt.Dimension(648, 15));

        labelDeskripsiUnpad7.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUnpad7.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUnpad7.setText("Presiden Susilo Bambang Yudhoyono.");
        labelDeskripsiUnpad7.setMaximumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad7.setMinimumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad7.setPreferredSize(new java.awt.Dimension(648, 15));

        labelDeskripsiUnpad8.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUnpad8.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUnpad8.setText("Penetapan itu didasarkan atas evaluasi kinerja yang");
        labelDeskripsiUnpad8.setMaximumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad8.setMinimumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad8.setPreferredSize(new java.awt.Dimension(648, 15));

        labelDeskripsiUnpad9.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUnpad9.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUnpad9.setText("dilakukan tim independen yang dibentuk oleh Kementerian");
        labelDeskripsiUnpad9.setMaximumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad9.setMinimumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad9.setPreferredSize(new java.awt.Dimension(648, 15));

        labelDeskripsiUnpad10.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUnpad10.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUnpad10.setText("Pendidikan dan Kebudayaan (Kemendikbud). Selain itu");
        labelDeskripsiUnpad10.setMaximumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad10.setMinimumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad10.setPreferredSize(new java.awt.Dimension(648, 15));

        labelDeskripsiUnpad11.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUnpad11.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUnpad11.setText("berdasarkan keputusan Badan Akreditasi Nasional Perguruan");
        labelDeskripsiUnpad11.setMaximumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad11.setMinimumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad11.setPreferredSize(new java.awt.Dimension(648, 15));

        labelDeskripsiUnpad12.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUnpad12.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUnpad12.setText("Tinggi (BAN PT) yang ditetapkan pada 16 Januari 2014.");
        labelDeskripsiUnpad12.setMaximumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad12.setMinimumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad12.setPreferredSize(new java.awt.Dimension(648, 15));

        labelDeskripsiUnpad13.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUnpad13.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUnpad13.setText("Unpad mendapat peringkat A.");
        labelDeskripsiUnpad13.setMaximumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad13.setMinimumSize(new java.awt.Dimension(648, 15));
        labelDeskripsiUnpad13.setPreferredSize(new java.awt.Dimension(648, 15));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(b3BarUnpad)
                .addGap(11, 11, 11)
                .addComponent(labelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bLogoutUnpad, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelLogoUnpad)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelAlamat2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelUnpad, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))
                            .addComponent(labelAlamat3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(labelAlamat1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelDeskripsiUnpad13, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDeskripsiUnpad12, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDeskripsiUnpad11, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDeskripsiUnpad10, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDeskripsiUnpad9, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDeskripsiUnpad1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelDeskripsiUnpad3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelDeskripsiUnpad2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(labelTentangKampusUnpad)
                                        .addGap(94, 94, 94)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelDeskripsiUnpad6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelDeskripsiUnpad4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(labelDeskripsiUnpad5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(labelDeskripsiUnpad7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(labelDeskripsiUnpad8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(b3BarUnpad))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bLogoutUnpad)
                            .addComponent(labelDashboard))))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelLogoUnpad)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelUnpad)
                        .addGap(6, 6, 6)
                        .addComponent(labelAlamat1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(labelAlamat2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(labelAlamat3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(labelTentangKampusUnpad)
                .addGap(19, 19, 19)
                .addComponent(labelDeskripsiUnpad1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUnpad2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUnpad3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUnpad4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUnpad5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUnpad6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUnpad7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(labelDeskripsiUnpad8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUnpad9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUnpad10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUnpad11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUnpad12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUnpad13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b3BarUnpadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3BarUnpadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3BarUnpadActionPerformed

    private void bLogoutUnpadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutUnpadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLogoutUnpadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCampProfileUnpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCampProfileUnpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCampProfileUnpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCampProfileUnpad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCampProfileUnpad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3BarUnpad;
    private javax.swing.JButton bLogoutUnpad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAlamat1;
    private javax.swing.JLabel labelAlamat2;
    private javax.swing.JLabel labelAlamat3;
    private javax.swing.JLabel labelDashboard;
    private javax.swing.JLabel labelDeskripsiUnpad1;
    private javax.swing.JLabel labelDeskripsiUnpad10;
    private javax.swing.JLabel labelDeskripsiUnpad11;
    private javax.swing.JLabel labelDeskripsiUnpad12;
    private javax.swing.JLabel labelDeskripsiUnpad13;
    private javax.swing.JLabel labelDeskripsiUnpad2;
    private javax.swing.JLabel labelDeskripsiUnpad3;
    private javax.swing.JLabel labelDeskripsiUnpad4;
    private javax.swing.JLabel labelDeskripsiUnpad5;
    private javax.swing.JLabel labelDeskripsiUnpad6;
    private javax.swing.JLabel labelDeskripsiUnpad7;
    private javax.swing.JLabel labelDeskripsiUnpad8;
    private javax.swing.JLabel labelDeskripsiUnpad9;
    private javax.swing.JLabel labelLogoUnpad;
    private javax.swing.JLabel labelTentangKampusUnpad;
    private javax.swing.JLabel labelUnpad;
    // End of variables declaration//GEN-END:variables
}
