package View;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import java.awt.event.MouseEvent;

/**
 *
 * @author Irsyad Muhamad Al Anshori
 * 
 */
public class viewSignUp extends javax.swing.JFrame {

    /**
     * Creates new form vSignUp
     */
    public viewSignUp() {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(360,640);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelWelcome = new javax.swing.JLabel();
        labelNgampusYuk = new javax.swing.JLabel();
        labelSignUp = new javax.swing.JLabel();
        tfFullName = new javax.swing.JTextField();
        tfGender = new javax.swing.JTextField();
        tfEmail = new javax.swing.JTextField();
        tfPassword = new javax.swing.JPasswordField();
        cboxAgree = new javax.swing.JCheckBox();
        bSignUp = new javax.swing.JButton();
        bLogin = new javax.swing.JButton();
        labelDontHaveAcc = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        labelWelcome.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        labelWelcome.setText("Welcome to");
        getContentPane().add(labelWelcome);
        labelWelcome.setBounds(115, 30, 117, 30);

        labelNgampusYuk.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        labelNgampusYuk.setText("NgampusYuk!");
        getContentPane().add(labelNgampusYuk);
        labelNgampusYuk.setBounds(107, 60, 133, 30);

        labelSignUp.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        labelSignUp.setText("SignUp");
        getContentPane().add(labelSignUp);
        labelSignUp.setBounds(143, 123, 68, 30);

        tfFullName.setText("Full Name");
        getContentPane().add(tfFullName);
        tfFullName.setBounds(50, 200, 260, 30);

        tfGender.setText("Gender");
        getContentPane().add(tfGender);
        tfGender.setBounds(50, 233, 260, 30);

        tfEmail.setText("Email or Phone Number");
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });
        getContentPane().add(tfEmail);
        tfEmail.setBounds(50, 266, 260, 30);

        tfPassword.setText("jPasswordField1");
        getContentPane().add(tfPassword);
        tfPassword.setBounds(50, 299, 260, 30);

        cboxAgree.setText("Agree to Our Terms & Condition");
        getContentPane().add(cboxAgree);
        cboxAgree.setBounds(50, 333, 179, 23);

        bSignUp.setBackground(new java.awt.Color(255, 255, 255));
        bSignUp.setForeground(new java.awt.Color(255, 255, 255));
        bSignUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Login.png"))); // NOI18N
        bSignUp.setBorder(null);
        bSignUp.setBorderPainted(false);
        bSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSignUpActionPerformed(evt);
            }
        });
        getContentPane().add(bSignUp);
        bSignUp.setBounds(290, 445, 1, 1);

        bLogin.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bLogin.setText("Login");
        bLogin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(bLogin);
        bLogin.setBounds(50, 540, 260, 40);

        labelDontHaveAcc.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDontHaveAcc.setText("Already have account?");
        getContentPane().add(labelDontHaveAcc);
        labelDontHaveAcc.setBounds(129, 517, 108, 15);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Grouping.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 360, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    private void bSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSignUpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bSignUpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bSignUp;
    private javax.swing.JLabel background;
    private javax.swing.JCheckBox cboxAgree;
    private javax.swing.JLabel labelDontHaveAcc;
    private javax.swing.JLabel labelNgampusYuk;
    private javax.swing.JLabel labelSignUp;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfFullName;
    private javax.swing.JTextField tfGender;
    private javax.swing.JPasswordField tfPassword;
    // End of variables declaration//GEN-END:variables

    public void addActionListener (ActionListener e) {
        bLogin.addActionListener(e);
        bSignUp.addActionListener(e);
    }

    public JButton getbLogin() {
        return bLogin;
    }

    public JButton getbSignUp() {
        return bSignUp;
    }

    public JCheckBox getCboxAgree() {
        return cboxAgree;
    }

    public String getTfEmail() {
        return tfEmail.getText();
    }

    public String getTfFullName() {
        return tfFullName.getText();
    }

    public String getTfGender() {
        return tfGender.getText();
    }

    public String getTfPassword() {
        return tfPassword.getText();
    }
    
    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }
}
