package View;

/**
 *
 * @author Ifdhal Hadi, Irsyad Muhamad Al Anhsori
 * 
 */
public class viewCampProfileITB extends javax.swing.JFrame {

    /**
     * Creates new form vCampProfileITB
     */
    public viewCampProfileITB() {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(360,640);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b3BarITB = new javax.swing.JButton();
        labelDashboard = new javax.swing.JLabel();
        bLogoutITB = new javax.swing.JButton();
        labelLogoITB = new javax.swing.JLabel();
        labelITB = new javax.swing.JLabel();
        labelAlamat1 = new javax.swing.JLabel();
        labelAlamat2 = new javax.swing.JLabel();
        labelTentangKampusITB = new javax.swing.JLabel();
        labelDeskripsiITB1 = new javax.swing.JLabel();
        labelDeskripsiITB2 = new javax.swing.JLabel();
        labelDeskripsiITB3 = new javax.swing.JLabel();
        labelDeskripsiITB4 = new javax.swing.JLabel();
        labelDeskripsiITB5 = new javax.swing.JLabel();
        labelDeskripsiITB6 = new javax.swing.JLabel();
        labelDeskripsiITB7 = new javax.swing.JLabel();
        labelDeskripsiITB8 = new javax.swing.JLabel();
        labelDeskripsiITB9 = new javax.swing.JLabel();
        labelDeskripsiITB10 = new javax.swing.JLabel();
        labelDeskripsiITB11 = new javax.swing.JLabel();
        labelDeskripsiITB12 = new javax.swing.JLabel();
        labelDeskripsiITB13 = new javax.swing.JLabel();
        labelDeskripsiITB14 = new javax.swing.JLabel();
        labelDeskripsiITB15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        b3BarITB.setBackground(new java.awt.Color(255, 255, 255));
        b3BarITB.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        b3BarITB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button 3 Bar.png"))); // NOI18N
        b3BarITB.setBorder(null);
        b3BarITB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3BarITBActionPerformed(evt);
            }
        });

        labelDashboard.setBackground(new java.awt.Color(255, 255, 255));
        labelDashboard.setFont(new java.awt.Font("Gill Sans MT", 1, 16)); // NOI18N
        labelDashboard.setText("NgampusYuk! Dashboard");

        bLogoutITB.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bLogoutITB.setText("Logout");
        bLogoutITB.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bLogoutITB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutITBActionPerformed(evt);
            }
        });

        labelLogoITB.setBackground(new java.awt.Color(255, 255, 255));
        labelLogoITB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Logo PT/Logo ITB.png"))); // NOI18N

        labelITB.setBackground(new java.awt.Color(255, 255, 255));
        labelITB.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        labelITB.setText("Institut Teknologi Bandung");

        labelAlamat1.setBackground(new java.awt.Color(255, 255, 255));
        labelAlamat1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelAlamat1.setText("Jl. Ganesha No. 10, Lb. Siliwangi Coblong,");

        labelAlamat2.setBackground(new java.awt.Color(255, 255, 255));
        labelAlamat2.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelAlamat2.setText("Kota. Bandung, Jawa Barat 40132");

        labelTentangKampusITB.setBackground(new java.awt.Color(255, 255, 255));
        labelTentangKampusITB.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        labelTentangKampusITB.setText("Tentang Kampus");

        labelDeskripsiITB1.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiITB1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiITB1.setText("Institut Teknologi Bandung (ITB) adalah sebuah perguruan");

        labelDeskripsiITB2.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiITB2.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiITB2.setText("tinggi negeri yang berkedudukan di Kota Bandujng. Nama ITB");

        labelDeskripsiITB3.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiITB3.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiITB3.setText("diresmikan pada tanggal 2 Maret 1959. Sejak tanggal 14");

        labelDeskripsiITB4.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiITB4.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiITB4.setText("Oktober 2013 ITB menjadi Perguruan Tinggi Negeri Badan");

        labelDeskripsiITB5.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiITB5.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiITB5.setText("Hukum (PTN BH) yang memiliki otonomi pengelolaan");

        labelDeskripsiITB6.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiITB6.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiITB6.setText("dalam akademik dan non-akademik. ITB telah memiliki 22");

        labelDeskripsiITB7.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiITB7.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiITB7.setText("program studi yang terakreditasi secara internasional");

        labelDeskripsiITB8.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiITB8.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiITB8.setText("(sebelas dari ABET, sebelas dari ASIIN).");

        labelDeskripsiITB9.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiITB9.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiITB9.setText("Kampus utama ITB saat ini merupakan lokasi dari sekolah");

        labelDeskripsiITB10.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiITB10.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiITB10.setText("tinggi teknik pertama di Indonesia sekaligus lembaga");

        labelDeskripsiITB11.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiITB11.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiITB11.setText("pendidikan tinggi pertama di Hindia Belanda. Walaupun");

        labelDeskripsiITB12.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiITB12.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiITB12.setText("masing-masing institusi pendidikan tinggi yang mengawali ITB");

        labelDeskripsiITB13.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiITB13.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiITB13.setText("memiliki karakteristik dan misi masing-masing, semuanya");

        labelDeskripsiITB14.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiITB14.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiITB14.setText("memberikan pengaruh dalam perkembangan yang menuju");

        labelDeskripsiITB15.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiITB15.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiITB15.setText("pada pendirian ITB.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(b3BarITB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(labelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bLogoutITB, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelLogoITB)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelITB)
                            .addComponent(labelAlamat1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(labelAlamat2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(labelTentangKampusITB)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelDeskripsiITB15, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDeskripsiITB14, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labelDeskripsiITB1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelDeskripsiITB2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                        .addComponent(labelDeskripsiITB4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelDeskripsiITB3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(labelDeskripsiITB5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDeskripsiITB6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDeskripsiITB7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDeskripsiITB8, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDeskripsiITB9, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDeskripsiITB10, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDeskripsiITB11, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDeskripsiITB12, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDeskripsiITB13, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(b3BarITB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bLogoutITB)
                            .addComponent(labelDashboard))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(labelLogoITB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(labelITB)
                        .addGap(6, 6, 6)
                        .addComponent(labelAlamat1)
                        .addGap(0, 0, 0)
                        .addComponent(labelAlamat2)))
                .addGap(39, 39, 39)
                .addComponent(labelTentangKampusITB)
                .addGap(19, 19, 19)
                .addComponent(labelDeskripsiITB1)
                .addGap(1, 1, 1)
                .addComponent(labelDeskripsiITB2)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiITB3)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiITB4)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiITB5)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiITB6)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiITB7)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiITB8)
                .addGap(15, 15, 15)
                .addComponent(labelDeskripsiITB9)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiITB10)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiITB11)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiITB12)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiITB13)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiITB14)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiITB15)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLogoutITBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutITBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLogoutITBActionPerformed

    private void b3BarITBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3BarITBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3BarITBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCampProfileITB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCampProfileITB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCampProfileITB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCampProfileITB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCampProfileITB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3BarITB;
    private javax.swing.JButton bLogoutITB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAlamat1;
    private javax.swing.JLabel labelAlamat2;
    private javax.swing.JLabel labelDashboard;
    private javax.swing.JLabel labelDeskripsiITB1;
    private javax.swing.JLabel labelDeskripsiITB10;
    private javax.swing.JLabel labelDeskripsiITB11;
    private javax.swing.JLabel labelDeskripsiITB12;
    private javax.swing.JLabel labelDeskripsiITB13;
    private javax.swing.JLabel labelDeskripsiITB14;
    private javax.swing.JLabel labelDeskripsiITB15;
    private javax.swing.JLabel labelDeskripsiITB2;
    private javax.swing.JLabel labelDeskripsiITB3;
    private javax.swing.JLabel labelDeskripsiITB4;
    private javax.swing.JLabel labelDeskripsiITB5;
    private javax.swing.JLabel labelDeskripsiITB6;
    private javax.swing.JLabel labelDeskripsiITB7;
    private javax.swing.JLabel labelDeskripsiITB8;
    private javax.swing.JLabel labelDeskripsiITB9;
    private javax.swing.JLabel labelITB;
    private javax.swing.JLabel labelLogoITB;
    private javax.swing.JLabel labelTentangKampusITB;
    // End of variables declaration//GEN-END:variables
}
