package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Irsyad Muhamad Al Anshori
 * 
 */
public class viewLogin extends javax.swing.JFrame {
    
    /**
     * Creates new form vLogin
     */
    public viewLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(360,640);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelWelcome = new javax.swing.JLabel();
        labelNgampusYuk = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        pfPassword = new javax.swing.JPasswordField();
        cboxRemember = new javax.swing.JCheckBox();
        bLogin = new javax.swing.JButton();
        labelDontHaveAcc = new javax.swing.JLabel();
        bSignUp = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        labelWelcome.setBackground(new java.awt.Color(255, 255, 255));
        labelWelcome.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        labelWelcome.setText("Welcome to");
        getContentPane().add(labelWelcome);
        labelWelcome.setBounds(115, 30, 117, 30);

        labelNgampusYuk.setBackground(new java.awt.Color(255, 255, 255));
        labelNgampusYuk.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        labelNgampusYuk.setText("NgampusYuk!");
        getContentPane().add(labelNgampusYuk);
        labelNgampusYuk.setBounds(107, 60, 133, 30);

        labelLogin.setBackground(new java.awt.Color(255, 255, 255));
        labelLogin.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        labelLogin.setText("Login");
        getContentPane().add(labelLogin);
        labelLogin.setBounds(150, 120, 52, 30);

        tfEmail.setText("Email or Phone Number");
        tfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEmailActionPerformed(evt);
            }
        });
        getContentPane().add(tfEmail);
        tfEmail.setBounds(50, 200, 260, 40);

        pfPassword.setText("jPasswordField1");
        getContentPane().add(pfPassword);
        pfPassword.setBounds(50, 255, 260, 40);

        cboxRemember.setBackground(new java.awt.Color(255, 255, 255));
        cboxRemember.setText("Remember Me");
        getContentPane().add(cboxRemember);
        cboxRemember.setBounds(50, 305, 130, 23);

        bLogin.setBackground(new java.awt.Color(255, 255, 255));
        bLogin.setForeground(new java.awt.Color(255, 255, 255));
        bLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Next.png"))); // NOI18N
        bLogin.setBorder(null);
        bLogin.setBorderPainted(false);
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });
        getContentPane().add(bLogin);
        bLogin.setBounds(290, 445, 31, 31);

        labelDontHaveAcc.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDontHaveAcc.setText("Don't have account?");
        getContentPane().add(labelDontHaveAcc);
        labelDontHaveAcc.setBounds(133, 517, 98, 15);

        bSignUp.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bSignUp.setText("Sign Up");
        bSignUp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(bSignUp);
        bSignUp.setBounds(50, 540, 260, 40);

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setFont(new java.awt.Font("Gill Sans MT", 1, 20)); // NOI18N
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Grouping.png"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 360, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLoginActionPerformed

    private void tfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JButton bSignUp;
    private javax.swing.JLabel background;
    private javax.swing.JCheckBox cboxRemember;
    private javax.swing.JLabel labelDontHaveAcc;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelNgampusYuk;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JPasswordField pfPassword;
    private javax.swing.JTextField tfEmail;
    // End of variables declaration//GEN-END:variables

    // BUTTON LOGIN
    
    public JButton getBLogin() {
        return bLogin;
    }
    
    public JCheckBox getCboxRemember() {
        return cboxRemember;
    }
       
    public JButton getBSignUp() {
        return bSignUp;
    }

    // TF LOGIN
    
    public String getTfEmail() {
        return tfEmail.getText();
    }

    public void setTfEmail(String x) {
        this.tfEmail.setText(x);
    }
    
    public String getPfPassword() {
        return pfPassword.getText();
    }
        
    public void setPfPassword(String x) {
        this.pfPassword.setText(x);
    }
    
    public void addActionListener (ActionListener e) {
        bLogin.addActionListener(e);
        bSignUp.addActionListener(e);
    }
    
    public void reset(){
        setTfEmail("");
        setPfPassword("");
    }
   
    public void showMessage(String message, String title, int type){
        JOptionPane.showMessageDialog(null, message, title, type);
    }
    
}
