package View;

/**
 *
 * @author Kamila Hanum
 * 
 */
public class viewCampProfileTelU extends javax.swing.JFrame {

    /**
     * Creates new form vCampProfileTelU
     */
    public viewCampProfileTelU() {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(360,640);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        b3BarTelU = new javax.swing.JButton();
        labelDashboard = new javax.swing.JLabel();
        bLogoutTelU = new javax.swing.JButton();
        labelLogoTelU = new javax.swing.JLabel();
        labelTelU = new javax.swing.JLabel();
        labelAlamat1 = new javax.swing.JLabel();
        labelAlamat2 = new javax.swing.JLabel();
        labelAlamat3 = new javax.swing.JLabel();
        labelTentangKampus = new javax.swing.JLabel();
        labelDeskripsiTelU1 = new javax.swing.JLabel();
        labelDeskripsiTelU2 = new javax.swing.JLabel();
        labelDeskripsiTelU3 = new javax.swing.JLabel();
        labelDeskripsiTelU4 = new javax.swing.JLabel();
        labelDeskripsiTelU5 = new javax.swing.JLabel();
        labelDeskripsiTelU6 = new javax.swing.JLabel();
        labelDeskripsiTelU7 = new javax.swing.JLabel();
        labelDeskripsiTelU8 = new javax.swing.JLabel();
        labelDeskripsiTelU9 = new javax.swing.JLabel();
        labelDeskripsiTelU10 = new javax.swing.JLabel();
        labelDeskripsiTelU11 = new javax.swing.JLabel();
        labelDeskripsiTelU12 = new javax.swing.JLabel();
        labelDeskripsiTelU13 = new javax.swing.JLabel();
        labelDeskripsiTelU14 = new javax.swing.JLabel();
        labelDeskripsiTelU15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        b3BarTelU.setBackground(new java.awt.Color(255, 255, 255));
        b3BarTelU.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        b3BarTelU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button 3 Bar.png"))); // NOI18N
        b3BarTelU.setBorder(null);
        b3BarTelU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3BarTelUActionPerformed(evt);
            }
        });

        labelDashboard.setBackground(new java.awt.Color(255, 255, 255));
        labelDashboard.setFont(new java.awt.Font("Gill Sans MT", 1, 16)); // NOI18N
        labelDashboard.setText("NgampusYuk! Dashboard");

        bLogoutTelU.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bLogoutTelU.setText("Logout");
        bLogoutTelU.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bLogoutTelU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutTelUActionPerformed(evt);
            }
        });

        labelLogoTelU.setBackground(new java.awt.Color(255, 255, 255));
        labelLogoTelU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Logo PT/Logo Tel-U.png"))); // NOI18N

        labelTelU.setBackground(new java.awt.Color(255, 255, 255));
        labelTelU.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        labelTelU.setText("Telkom University  (Tel-U)");

        labelAlamat1.setBackground(new java.awt.Color(255, 255, 255));
        labelAlamat1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelAlamat1.setText("Jl. Telekomunikasi, Jl. Terusan Buah Batu");

        labelAlamat2.setBackground(new java.awt.Color(255, 255, 255));
        labelAlamat2.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelAlamat2.setText("No.01, Sukapura, Kec. Dayeuhkolot,");
        labelAlamat2.setPreferredSize(new java.awt.Dimension(217, 15));

        labelAlamat3.setBackground(new java.awt.Color(255, 255, 255));
        labelAlamat3.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelAlamat3.setText("Bandung, Jawa Barat 40257");
        labelAlamat3.setPreferredSize(new java.awt.Dimension(217, 15));

        labelTentangKampus.setBackground(new java.awt.Color(255, 255, 255));
        labelTentangKampus.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        labelTentangKampus.setText("Tentang Kampus");

        labelDeskripsiTelU1.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiTelU1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiTelU1.setText("Universitas Telkom atau disingkat Tel-U, adalah sebuah");

        labelDeskripsiTelU2.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiTelU2.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiTelU2.setText("perguruan tinggi swasta di Indonesia. Kampus utama Tel-U");

        labelDeskripsiTelU3.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiTelU3.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiTelU3.setText("terletak di Kabupaten Bandung, Jawa Barat, tepatnya di Jalan");

        labelDeskripsiTelU4.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiTelU4.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiTelU4.setText("Telekomunikasi - Terusan Buahbatu, di kawasan Bandung");

        labelDeskripsiTelU5.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiTelU5.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiTelU5.setText("Technoplex (BT-Plex). Kampus lainnya berlokasi di daerah");

        labelDeskripsiTelU6.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiTelU6.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiTelU6.setText("Gegerkalong Hilir, sebelah utara Kota Bandung, di Kompleks");

        labelDeskripsiTelU7.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiTelU7.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiTelU7.setText("Perkantoran PT. Telkom (Telkom Innovation and");

        labelDeskripsiTelU8.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiTelU8.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiTelU8.setText("Development Center dan Telkom Corporate University / ");

        labelDeskripsiTelU9.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiTelU9.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiTelU9.setText("Telkom Training Center).");

        labelDeskripsiTelU10.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiTelU10.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiTelU10.setText("Telkom University merupakan penggabungan dari empat");

        labelDeskripsiTelU11.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiTelU11.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiTelU11.setText("institusi di bawah badan penyelenggara Yayasan Pendidikan");

        labelDeskripsiTelU12.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiTelU12.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiTelU12.setText("Telkom (YPT), yaitu Institut Teknologi Telkom (IT Telkom),");

        labelDeskripsiTelU13.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiTelU13.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiTelU13.setText("Institut Manajemen Telkom (IM Telkom), Politeknik Telkom,");

        labelDeskripsiTelU14.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiTelU14.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiTelU14.setText("dan Sekolah Tinggi Seni Rupa dan Desain Indonesia Telkom ");

        labelDeskripsiTelU15.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiTelU15.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiTelU15.setText("(STISI Telkom).");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(labelTentangKampus))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelLogoTelU)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(labelTelU))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(labelAlamat1))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(labelAlamat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelAlamat3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(b3BarTelU)
                        .addGap(11, 11, 11)
                        .addComponent(labelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bLogoutTelU, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDeskripsiTelU9)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(labelDeskripsiTelU11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDeskripsiTelU8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDeskripsiTelU4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDeskripsiTelU2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(labelDeskripsiTelU1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelDeskripsiTelU3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDeskripsiTelU5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDeskripsiTelU6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDeskripsiTelU7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDeskripsiTelU12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDeskripsiTelU13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDeskripsiTelU14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDeskripsiTelU15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelDeskripsiTelU10, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(bLogoutTelU))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(b3BarTelU))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(labelDashboard)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(labelTelU)
                        .addGap(6, 6, 6)
                        .addComponent(labelAlamat1)
                        .addGap(0, 0, 0)
                        .addComponent(labelAlamat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(labelAlamat3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(labelLogoTelU, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(labelTentangKampus)
                .addGap(19, 19, 19)
                .addComponent(labelDeskripsiTelU1)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiTelU2)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiTelU3)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiTelU4)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiTelU5)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiTelU6)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiTelU7)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiTelU8)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiTelU9)
                .addGap(15, 15, 15)
                .addComponent(labelDeskripsiTelU10)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiTelU11)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiTelU12)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiTelU13)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiTelU14)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiTelU15)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b3BarTelUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3BarTelUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3BarTelUActionPerformed

    private void bLogoutTelUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutTelUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLogoutTelUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCampProfileTelU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCampProfileTelU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCampProfileTelU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCampProfileTelU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCampProfileTelU().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3BarTelU;
    private javax.swing.JButton bLogoutTelU;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelAlamat1;
    private javax.swing.JLabel labelAlamat2;
    private javax.swing.JLabel labelAlamat3;
    private javax.swing.JLabel labelDashboard;
    private javax.swing.JLabel labelDeskripsiTelU1;
    private javax.swing.JLabel labelDeskripsiTelU10;
    private javax.swing.JLabel labelDeskripsiTelU11;
    private javax.swing.JLabel labelDeskripsiTelU12;
    private javax.swing.JLabel labelDeskripsiTelU13;
    private javax.swing.JLabel labelDeskripsiTelU14;
    private javax.swing.JLabel labelDeskripsiTelU15;
    private javax.swing.JLabel labelDeskripsiTelU2;
    private javax.swing.JLabel labelDeskripsiTelU3;
    private javax.swing.JLabel labelDeskripsiTelU4;
    private javax.swing.JLabel labelDeskripsiTelU5;
    private javax.swing.JLabel labelDeskripsiTelU6;
    private javax.swing.JLabel labelDeskripsiTelU7;
    private javax.swing.JLabel labelDeskripsiTelU8;
    private javax.swing.JLabel labelDeskripsiTelU9;
    private javax.swing.JLabel labelLogoTelU;
    private javax.swing.JLabel labelTelU;
    private javax.swing.JLabel labelTentangKampus;
    // End of variables declaration//GEN-END:variables
}
