package View;

/**
 *
 * @author Ifdhal Hadi, Irsyad Muhamad Al Anshori
 * 
 */
public class viewCampProfileUPI extends javax.swing.JFrame {

    /**
     * Creates new form vCampProfileUPI
     */
    public viewCampProfileUPI() {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(360,640);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b3BarITB = new javax.swing.JButton();
        labelDashboard = new javax.swing.JLabel();
        bLogoutUPI = new javax.swing.JButton();
        labelLogoUPI = new javax.swing.JLabel();
        labelUPI = new javax.swing.JLabel();
        labelAlamat1 = new javax.swing.JLabel();
        labelAlamat2 = new javax.swing.JLabel();
        labelTentangKampus = new javax.swing.JLabel();
        labelDeskripsiUPI1 = new javax.swing.JLabel();
        labelDeskripsiUPI2 = new javax.swing.JLabel();
        labelDeskripsiUPI3 = new javax.swing.JLabel();
        labelDeskripsiUPI4 = new javax.swing.JLabel();
        labelDeskripsiUPI5 = new javax.swing.JLabel();
        labelDeskripsiUPI6 = new javax.swing.JLabel();
        labelDeskripsiUPI7 = new javax.swing.JLabel();
        labelDeskripsiUPI8 = new javax.swing.JLabel();
        labelDeskripsiUPI9 = new javax.swing.JLabel();
        labelDeskripsiUPI10 = new javax.swing.JLabel();
        labelDeskripsiUPI11 = new javax.swing.JLabel();
        labelDeskripsiUPI12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        b3BarITB.setBackground(new java.awt.Color(255, 255, 255));
        b3BarITB.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        b3BarITB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button 3 Bar.png"))); // NOI18N
        b3BarITB.setBorder(null);
        b3BarITB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3BarITBActionPerformed(evt);
            }
        });

        labelDashboard.setBackground(new java.awt.Color(255, 255, 255));
        labelDashboard.setFont(new java.awt.Font("Gill Sans MT", 1, 16)); // NOI18N
        labelDashboard.setText("NgampusYuk! Dashboard");

        bLogoutUPI.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bLogoutUPI.setText("Logout");
        bLogoutUPI.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelLogoUPI.setBackground(new java.awt.Color(255, 255, 255));
        labelLogoUPI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Logo PT/Logo UPI.png"))); // NOI18N

        labelUPI.setBackground(new java.awt.Color(255, 255, 255));
        labelUPI.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        labelUPI.setText("Universitas Pendidikan Indonesia");

        labelAlamat1.setBackground(new java.awt.Color(255, 255, 255));
        labelAlamat1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelAlamat1.setText("Jl. Dr. Setiabudi, No. 229, Isola, Sukasari");

        labelAlamat2.setBackground(new java.awt.Color(255, 255, 255));
        labelAlamat2.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelAlamat2.setText("Kota. Bandung, Jawa Barat 40154");

        labelTentangKampus.setBackground(new java.awt.Color(255, 255, 255));
        labelTentangKampus.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        labelTentangKampus.setText("Tentang Kampus");

        labelDeskripsiUPI1.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUPI1.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUPI1.setText("Universitas Pendidikan Indonesia (UPI) adalah sebuah");

        labelDeskripsiUPI2.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUPI2.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUPI2.setText("perguruan tinggi negeri yang kampus utamanya berkedudukan");

        labelDeskripsiUPI3.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUPI3.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUPI3.setText("di Kota Bandung, Jawa Barat, Indonesia. Sejak tahun 2012,");

        labelDeskripsiUPI4.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUPI4.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUPI4.setText("UPI berstatus sebagai Perguruan Tinggi yang diselenggarakan");

        labelDeskripsiUPI5.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUPI5.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUPI5.setText("Pemerintah (PTP), berubah dari perguruan tinggi Badan");

        labelDeskripsiUPI6.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUPI6.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUPI6.setText("Hukum Milik Negara (BHMN).");

        labelDeskripsiUPI7.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUPI7.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUPI7.setText("UPI adalah perguruan tinggi yang menganut sistem");

        labelDeskripsiUPI8.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUPI8.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUPI8.setText("multikampus yaitu dengan 6 kampus yang tersebar di dua");

        labelDeskripsiUPI9.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUPI9.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUPI9.setText("Provinsi yaitu Jawa Barat dan Banten. Kampus utama UPI");

        labelDeskripsiUPI10.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUPI10.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUPI10.setText("berlokasi di Jalan Setiabudhi 229, Bandung. Sedangkan");

        labelDeskripsiUPI11.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUPI11.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUPI11.setText("kampus lainnya berlokasi di Cibiru, Tasikmalaya, Purwakarta,");

        labelDeskripsiUPI12.setBackground(new java.awt.Color(255, 255, 255));
        labelDeskripsiUPI12.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelDeskripsiUPI12.setText("dan Serang.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(b3BarITB)
                .addGap(11, 11, 11)
                .addComponent(labelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bLogoutUPI, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelLogoUPI)
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAlamat2)
                            .addComponent(labelAlamat1)
                            .addComponent(labelUPI)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(labelTentangKampus)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelDeskripsiUPI4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDeskripsiUPI3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDeskripsiUPI2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(labelDeskripsiUPI1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDeskripsiUPI5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDeskripsiUPI6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDeskripsiUPI8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDeskripsiUPI7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDeskripsiUPI9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDeskripsiUPI10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDeskripsiUPI11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelDeskripsiUPI12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bLogoutUPI)
                            .addComponent(labelDashboard)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(b3BarITB)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(labelLogoUPI)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelUPI)
                        .addGap(6, 6, 6)
                        .addComponent(labelAlamat1)
                        .addGap(0, 0, 0)
                        .addComponent(labelAlamat2)))
                .addGap(39, 39, 39)
                .addComponent(labelTentangKampus)
                .addGap(19, 19, 19)
                .addComponent(labelDeskripsiUPI1)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUPI2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUPI3)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUPI4)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUPI5)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUPI6)
                .addGap(15, 15, 15)
                .addComponent(labelDeskripsiUPI7)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUPI8)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUPI9)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUPI10)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUPI11)
                .addGap(0, 0, 0)
                .addComponent(labelDeskripsiUPI12)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b3BarITBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3BarITBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_b3BarITBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCampProfileUPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCampProfileUPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCampProfileUPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCampProfileUPI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCampProfileUPI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3BarITB;
    private javax.swing.JButton bLogoutUPI;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAlamat1;
    private javax.swing.JLabel labelAlamat2;
    private javax.swing.JLabel labelDashboard;
    private javax.swing.JLabel labelDeskripsiUPI1;
    private javax.swing.JLabel labelDeskripsiUPI10;
    private javax.swing.JLabel labelDeskripsiUPI11;
    private javax.swing.JLabel labelDeskripsiUPI12;
    private javax.swing.JLabel labelDeskripsiUPI2;
    private javax.swing.JLabel labelDeskripsiUPI3;
    private javax.swing.JLabel labelDeskripsiUPI4;
    private javax.swing.JLabel labelDeskripsiUPI5;
    private javax.swing.JLabel labelDeskripsiUPI6;
    private javax.swing.JLabel labelDeskripsiUPI7;
    private javax.swing.JLabel labelDeskripsiUPI8;
    private javax.swing.JLabel labelDeskripsiUPI9;
    private javax.swing.JLabel labelLogoUPI;
    private javax.swing.JLabel labelTentangKampus;
    private javax.swing.JLabel labelUPI;
    // End of variables declaration//GEN-END:variables
}
