package View;

/**
 *
 * @author Ifdhal Hadi
 * 
 */
public class viewMenuUser extends javax.swing.JFrame {

    /**
     * Creates new form MenuUser
     */
    public viewMenuUser() {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(360,640);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b3BarMUser = new javax.swing.JButton();
        labelDashboard = new javax.swing.JLabel();
        bLogoutMUser = new javax.swing.JButton();
        bTestMBTI = new javax.swing.JButton();
        labelTestMBTI = new javax.swing.JLabel();
        bCollegeInfo = new javax.swing.JButton();
        labelCollegeInfo = new javax.swing.JLabel();
        bMBTIResult = new javax.swing.JButton();
        labelMBTIResult = new javax.swing.JLabel();
        bAnnounce = new javax.swing.JButton();
        labelAnnounce = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        b3BarMUser.setBackground(new java.awt.Color(255, 255, 255));
        b3BarMUser.setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        b3BarMUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button 3 Bar.png"))); // NOI18N
        b3BarMUser.setBorder(null);

        labelDashboard.setFont(new java.awt.Font("Gill Sans MT", 1, 16)); // NOI18N
        labelDashboard.setText("NgampusYuk! Dashboard");

        bLogoutMUser.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        bLogoutMUser.setText("Logout");
        bLogoutMUser.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bLogoutMUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutMUserActionPerformed(evt);
            }
        });

        bTestMBTI.setBackground(new java.awt.Color(255, 255, 255));
        bTestMBTI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Test MBTI.png"))); // NOI18N
        bTestMBTI.setBorder(null);
        bTestMBTI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTestMBTIActionPerformed(evt);
            }
        });

        labelTestMBTI.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelTestMBTI.setText("Test MBTI");

        bCollegeInfo.setBackground(new java.awt.Color(255, 255, 255));
        bCollegeInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button College.png"))); // NOI18N
        bCollegeInfo.setBorder(null);
        bCollegeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCollegeInfoActionPerformed(evt);
            }
        });

        labelCollegeInfo.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelCollegeInfo.setText("College Information");

        bMBTIResult.setBackground(new java.awt.Color(255, 255, 255));
        bMBTIResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button MBTI Result.png"))); // NOI18N
        bMBTIResult.setBorder(null);
        bMBTIResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bMBTIResultActionPerformed(evt);
            }
        });

        labelMBTIResult.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelMBTIResult.setText("MBTI Result");

        bAnnounce.setBackground(new java.awt.Color(255, 255, 255));
        bAnnounce.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Button Announce.png"))); // NOI18N
        bAnnounce.setBorder(null);
        bAnnounce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAnnounceActionPerformed(evt);
            }
        });

        labelAnnounce.setFont(new java.awt.Font("Gill Sans MT", 0, 12)); // NOI18N
        labelAnnounce.setText("Announcement");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(b3BarMUser)
                .addGap(11, 11, 11)
                .addComponent(labelDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bLogoutMUser, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTestMBTI)
                        .addGap(64, 64, 64)
                        .addComponent(labelCollegeInfo))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bTestMBTI, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(39, 39, 39)
                            .addComponent(bCollegeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bMBTIResult, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(labelMBTIResult)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(15, 15, 15)
                                    .addComponent(labelAnnounce))
                                .addComponent(bAnnounce, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(b3BarMUser))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bLogoutMUser)
                            .addComponent(labelDashboard))))
                .addGap(123, 123, 123)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bCollegeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bTestMBTI, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTestMBTI)
                    .addComponent(labelCollegeInfo))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bAnnounce, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bMBTIResult, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMBTIResult)
                    .addComponent(labelAnnounce))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bTestMBTIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTestMBTIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bTestMBTIActionPerformed

    private void bLogoutMUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutMUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bLogoutMUserActionPerformed

    private void bCollegeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCollegeInfoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCollegeInfoActionPerformed

    private void bMBTIResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMBTIResultActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bMBTIResultActionPerformed

    private void bAnnounceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAnnounceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bAnnounceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewMenuUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewMenuUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3BarMUser;
    private javax.swing.JButton bAnnounce;
    private javax.swing.JButton bCollegeInfo;
    private javax.swing.JButton bLogoutMUser;
    private javax.swing.JButton bMBTIResult;
    private javax.swing.JButton bTestMBTI;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAnnounce;
    private javax.swing.JLabel labelCollegeInfo;
    private javax.swing.JLabel labelDashboard;
    private javax.swing.JLabel labelMBTIResult;
    private javax.swing.JLabel labelTestMBTI;
    // End of variables declaration//GEN-END:variables
}
